wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1677142940.954276
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.13.10
      8:
      - 5
batch_size:
  desc: null
  value: 1
cra:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
epochs_per_save:
  desc: null
  value: 1
itersup:
  desc: null
  value: false
log:
  desc: null
  value: bs+1+_lr+0.0001+_epoch+100
lossvar:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0001
num_workers:
  desc: null
  value: 12
optimizer:
  desc: null
  value: adam
pr:
  desc: null
  value: bj
reg_ch:
  desc: null
  value: 512
reg_hw:
  desc: null
  value: 2
resume_from_epoch:
  desc: null
  value: ''
resume_sametr:
  desc: null
  value: false
save_command:
  desc: null
  value: false
shapeloss:
  desc: null
  value: false
sup_aug_IUV:
  desc: null
  value: 1
sup_aug_j2d:
  desc: null
  value: 1
sup_aug_vertex:
  desc: null
  value: 1
valaug:
  desc: null
  value: 1
valdata:
  desc: null
  value: ''
vertloss:
  desc: null
  value: 1
